### CREATE TRIP
POST http://localhost:3333/trips
Content-Type: application/json

{
  "destination": "Floriánopolis",
  "starts_at": "2024-07-10T18:00:00",
  "ends_at": "2024-07-20T18:00:00",
  "owner_name": "Matheus Reinheimer",
  "owner_email": "mreinheimer0@gmail.com",
  "emails_to_invite": [
    "mreinheimer0@gmail.com",
    "johndoe@acme.com"
  ]
}

### CONFIRM TRIP
GET http://localhost:3333/trips/1fbc0ae8-1cbe-4cc0-bf84-92b3a5b7212a/confirm

### CONFIRM PARTICIPANT
GET http://localhost:3333/participants/ba41b33e-23d8-45e7-99e1-69f488a65241/confirm